sudo: required

language: java

services:
  - docker

script:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin # put aws-cli in the path
  - sudo curl -o /usr/local/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
  - sudo chmod +x /usr/local/bin/ecs-cli
  - eval $(aws ecr get-login --region us-east-2 | sed 's/-e none//') #needs AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY envvars
  - ecs-cli configure --cluster awsdemo --region us-east-2
  - ./gradlew pushImage
  - ecs-cli compose --file docker/awsdemo-compose.yml service down
  - sleep 5
  - ecs-cli compose --file docker/awsdemo-compose.yml service up