version: 1
task_definition:
  task_execution_role: ecsExecutionRole
  ecs_network_mode: awsvpc
  task_size:
    mem_limit: 1.5GB
    cpu_limit: 256
run_params:
  network_configuration:
    awsvpc_configuration:
      subnets:
        - "subnet-fcc7b5d3"
        - "subnet-3e5f6575"
      security_groups:
        - "sg-913a9fe6"
      assign_public_ip: ENABLED